In [1]:
import pandas as pd

In [3]:
#raeding the csv file
df=pd.read_csv("StudentsPerformance.csv")
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

# Rename Column
The rename() method in pandas is used to change the labels of rows (index) or columns in a DataFrame or Series.

**📌 Basic Syntax:**

DataFrame.rename(mapper=None, index=None, columns=None, inplace=False)

**🔑 Parameters:**

**columns:** Dictionary to rename column names

**index:** Dictionary to rename index labels

**inplace:**

True → modifies original DataFrame

False → returns a new DataFrame (default)

In [7]:
# rename column and overwrite the values of the dataframe
df=df.rename(columns={'gender':'Gender'})
df

,Gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [8]:
#rename multiple columns and update the dataframe with the inplace argument
df.rename(columns={'race/ethnicity':'Race/Ethnicity','math score':'math score'.title()},inplace=True)
df

,Gender,Race/Ethnicity,parental level of education,lunch,test preparation course,Math Score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86