In [1]:
#importing pandas
import pandas as pd

In [2]:
#reading csv file
df=pd.read_csv("StudentsPerformance.csv")

In [3]:
#showing the dataframe
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

# 1. ATTRIBUTES

In [4]:
# shape attribute -- to get dimensions
df.shape

(1000, 8)

In [5]:
#index attribute - gives start,end and step size for the indexes
df.index

RangeIndex(start=0, stop=1000, step=1)

In [6]:
# getting acces to column attribute - column attribute
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [7]:
# data types of each columns- dtypes attribute
df.dtypes

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

# Methods

In [8]:
# showing first 5 rows
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [9]:
# showing the info of the dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [10]:
#describing basic stattistics of the dataframe
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

# 3.Functions

In [11]:
# getting the len of dataframe(no if entries)
len(df)

1000

In [12]:
# obtaing the highest index of the dataframe
max(df.index)

999

In [13]:
#obtaining the lowest index of the dataframe
min(df.index)

0

In [14]:
#obtaining the datatype
type(df)

pandas.core.frame.DataFrame

In [15]:
#rounding the values of the dataframe
round(df,2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

# Selecting one column

## 1.1 Syntax 1

In [16]:
# selcting a column using [] (prefeered way)

df['gender']

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [17]:
#checking the datatype- series
type(df['gender'])

pandas.core.series.Series

In [18]:
# SERIES: attributes and methods
print(df['gender'].index)
print(df['gender'].head())

RangeIndex(start=0, stop=1000, step=1)
0    female
1    female
2    female
3      male
4      male
Name: gender, dtype: object

## 1.2 Syntax 2

In [19]:
# selecting a column with .
df.gender

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [20]:
# select a column with . (pitfalls)
df.math score # does not understand the space betwen the column - would give syntax error

SyntaxError: invalid syntax (3943282378.py, line 2)

In [ ]:
# select the same colujmn using []
df['math score']