In [1]:
import pandas as pd

In [2]:
# reading the csv file
df=pd.read_csv("StudentsPerformance.csv")
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

# 1 Adding a new column

## 1.1 assign()
When to use assign ?

-Add multiple columns in a single line of code.

-When you need to overwrite the values of an existing columns(best practice).
    
**IMPORTANT** : It returns a new object(copy) withh all original columns in addition to the new ones. Follow Immutable style-> **original data safe**

In [3]:
 import numpy as np

In [4]:
#create random numbers for our new score columns
score1=np.random.randint(low=1,high=100,size=1000)
score2=np.random.randint(low=1,high=100,size=1000)

In [5]:
#create the Series using the random numbers
series1=pd.Series(score1,index=np.arange(0,1000))
series2=pd.Series(score2,index=np.arange(0,1000))

In [6]:
#using assign() to add multiple columns
df.assign(score1=series1,score2=series2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,score1,score2
0,female,group B,bachelor's degree,standard,none,72,72,74,71,3
1,female,group C,some college,standard,completed,69,90,88,59,7
2,female,group B,master's degree,standard,none,90,95,93,96,97
3,male,group A,associate's degree,free/reduced,none,47,57,44,16,4
4,male,group C,some college,standard,none,76,78,75,46,18
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,81,92
996,male,group C,high school,free/reduced,none,62,55,55,72,23
997,female,group C,high school,free/reduced,completed,59,71,65,49,59
998,female,group D,some college,standard,completed,68,78,77,40,3
999,female,group D,some college,free/reduced,none,77,86,86,70,35

In [7]:
#assign method only creates a copy original remanins unaffected
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [8]:
# to replicate the chnages in the orignal dataframe
df=df.assign(score1=series1,score2=series2)

In [9]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,score1,score2
0,female,group B,bachelor's degree,standard,none,72,72,74,71,3
1,female,group C,some college,standard,completed,69,90,88,59,7
2,female,group B,master's degree,standard,none,90,95,93,96,97
3,male,group A,associate's degree,free/reduced,none,47,57,44,16,4
4,male,group C,some college,standard,none,76,78,75,46,18
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,81,92
996,male,group C,high school,free/reduced,none,62,55,55,72,23
997,female,group C,high school,free/reduced,completed,59,71,65,49,59
998,female,group D,some college,standard,completed,68,78,77,40,3
999,female,group D,some college,free/reduced,none,77,86,86,70,35

## 1.2 insert()
Inserts a new column at a specific position or index.
It does not return anything.
**It modifies the DataFrame directly (in-place)**
**Syntax: df.insert(loc,column,value)**

In [10]:
#using index to add a coluumn at a specific position
df.insert(8,"language score",np.random.randint(low=1,high=100,size=1000))

In [11]:
# show the dataframe
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2
0,female,group B,bachelor's degree,standard,none,72,72,74,43,71,3
1,female,group C,some college,standard,completed,69,90,88,24,59,7
2,female,group B,master's degree,standard,none,90,95,93,81,96,97
3,male,group A,associate's degree,free/reduced,none,47,57,44,70,16,4
4,male,group C,some college,standard,none,76,78,75,45,46,18
...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,70,81,92
996,male,group C,high school,free/reduced,none,62,55,55,32,72,23
997,female,group C,high school,free/reduced,completed,59,71,65,95,49,59
998,female,group D,some college,standard,completed,68,78,77,3,40,3
999,female,group D,some college,free/reduced,none,77,86,86,63,70,35

In [ ]:
# no need to use the assignment operator to assign the new column