In [1]:
import pandas as pd

In [2]:
# reads csv file
df = pd.read_csv('players_20.csv')

# set index
df.set_index('short_name', inplace=True)
# select column

df = df[['long_name', 'age', 'dob', 'height_cm', 'weight_kg', 'nationality', 'club']]

In [3]:
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

# copy()

the .copy() function is used to create a copy of a DataFrame or Series.

**📌 Why .copy() is important**

Without .copy(), sometimes variables may share the same data, so changing one can unintentionally change the other.

**📌 Syntax**

df_copy = df.copy(deep=True)

**📌 Without .copy() (problem case)**

df2 = df   # no copy, just reference

df2['A'][0] = 100

print(df)   # also changes!

👉 Both change because they point to the same object

## 1 DEEP COPY
df_copy = df.copy(deep=True)

Completely independent copy

Changes do NOT affect original

In [4]:
df_copy=df.copy()
df_copy.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

In [5]:
# update value in original dataframe

df['height_cm']=170
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,170,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,170,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,170,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,170,74,Belgium,Real Madrid

In [6]:
# copy vs original dataframe
df_copy.head()

df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,170,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,170,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,170,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,170,74,Belgium,Real Madrid

## 2 SHALLOW COPY
df_copy = df.copy(deep=False)

Shares underlying data

Changes may affect both

In [7]:
df_copy=df.copy(deep=False)
df_copy.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,170,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,170,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,170,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,170,74,Belgium,Real Madrid

In [8]:
# update value in original dataframe

In [9]:
# shallow copy vs deep copy