In [1]:
import pandas as pd

In [2]:
# reads csv file
df = pd.read_csv('players_20.csv')

# set index
df.set_index('short_name', inplace=True)
# select column

df = df[['long_name', 'age', 'dob', 'height_cm', 'weight_kg', 'nationality', 'club']]

In [3]:
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

# query()
.query() is used to filter rows of a DataFrame using a condition written as a string.

👉 It’s an alternative to:

df[df['age'] > 18]

🔹Basic Syntax:

df.query("condition")

🔴 Important Notes:

You must pass condition as a string.

Column names are used directly (no df['col']).

Use @ for external variables

✅ Simple condition: 
df.query("age > 18")

✅ Multiple conditions: 
df.query("age > 18 and salary > 50000")

✅ Using OR: 
df.query("age > 18 or salary > 50000")

✅ Using variables (important): 

limit = 18

df.query("age > @limit")

✅ Column names with spaces: 
df.query(" `total salary` > 50000")

👉 Use backticks `

In [15]:
# select players older than 34
df.query(" age > 34 ").head()

# exercise: write the equivalent boolean indexing
df[df['age']>34].head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Z. Ibrahimović,Zlatan Ibrahimović,37,1981-10-03,195,95,Sweden,LA Galaxy
Pepe,Képler Laveran Lima Ferreira,36,1983-02-26,188,81,Portugal,FC Porto
G. Buffon,Gianluigi Buffon,41,1978-01-28,192,92,Italy,Juventus
Casillas,Iker Casillas Fernández,38,1981-05-20,185,84,Spain,FC Porto
F. Quagliarella,Fabio Quagliarella,36,1983-01-31,180,79,Italy,Sampdoria

In [19]:
# select player older than 34 and from Italy
df.query(" age>34 and nationality=='Italy' ").head()

# using boolean indexing
df[(df['age']>34) & (df['nationality']=='Italy')].head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
G. Buffon,Gianluigi Buffon,41,1978-01-28,192,92,Italy,Juventus
F. Quagliarella,Fabio Quagliarella,36,1983-01-31,180,79,Italy,Sampdoria
D. De Rossi,Daniele De Rossi,35,1983-07-24,184,83,Italy,Boca Juniors
A. Mirante,Antonio Mirante,35,1983-07-08,193,79,Italy,Roma
A. Diamanti,Alessandro Diamanti,36,1983-05-02,180,75,Italy,Western United FC

In [21]:
# add a not operator to first example
df.query("not (age>34 and nationality=='Italy') ").head()

# boolean
df[~((df['age']>34) & (df['nationality']=='Italy'))].head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid