In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('laptop_price.csv',encoding='unicode_escape')

In [4]:
df.head(3)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00

# 1 drop_duplicates()

the drop_duplicates() method is used to remove duplicate rows from a DataFrame (or duplicate values from a Series).

🔹 📌 Basic Idea

Keeps only unique rows.
Removes repeated entries based on column values

🔹 ✅ Syntax

df.drop_duplicates(subset=None, keep='first', inplace=False)

Parameters:

subset → column(s) to check duplicates

keep → which duplicate to keep:

    'first' (default): keep first, remove rest
   
    'last': keep last, remove others
    
    False: remove all duplicates
    
    inplace → modify original DataFrame (True/False)

In [10]:
# drop duplicates in 2 or more columns
df.drop_duplicates(subset=['Company'],keep='first')[['Company','Price_euros']]

       Company  Price_euros
0        Apple      1339.69
2           HP       575.00
5         Acer       400.00
8         Asus      1495.00
13        Dell       498.90
18      Lenovo       499.00
30       Chuwi       244.99
58         MSI      2449.00
70   Microsoft      1089.00
143    Toshiba       602.00
170     Huawei      1349.00
184     Xiaomi      1199.00
191       Vero       260.00
196      Razer      6099.00
429   Mediacom       299.00
430    Samsung       269.00
437     Google      2199.00
567    Fujitsu       739.00
678         LG      2299.00

In [14]:
# sort dataframe ascending by company and price
#cheapest first and most expensive last
df_sorted=df.sort_values(['Company','Price_euros'])

In [18]:
# cheapest first
df_cheapest=df_sorted.drop_duplicates(subset=['Company'],keep='first')
df_cheapest[['Company','Price_euros']]

        Company  Price_euros
1215       Acer       174.00
1         Apple       898.94
20         Asus       191.90
30        Chuwi       244.99
340        Dell       274.90
983     Fujitsu       649.00
472      Google      1275.00
1268         HP       209.00
170      Huawei      1349.00
909          LG      1899.00
1272     Lenovo       229.00
1169        MSI       839.00
626    Mediacom       239.00
457   Microsoft       989.00
1117      Razer      1029.00
430     Samsung       269.00
159     Toshiba       447.00
1120       Vero       196.00
877      Xiaomi       935.00

In [19]:
#most expensive
df_expensive=df_sorted.drop_duplicates(subset=['Company'],keep='last')
df_expensive[['Company','Price_euros']]

        Company  Price_euros
1189       Acer      2599.00
17        Apple      2858.00
1066       Asus      3975.00
421       Chuwi       449.00
723        Dell      3659.40
623     Fujitsu       799.00
437      Google      2199.00
749          HP      4389.00
214      Huawei      1499.00
678          LG      2299.00
610      Lenovo      4899.00
177         MSI      2799.00
580    Mediacom       389.00
449   Microsoft      2589.00
196       Razer      6099.00
874     Samsung      1849.00
491     Toshiba      2799.00
191        Vero       260.00
514      Xiaomi      1399.95

In [22]:
# ARGUMENTS

#inplace:default False , when True make changes to original dataframe
#ignore_index=True: resulting axis will be labeled 0,1,..

df_expensive=df_sorted.drop_duplicates(subset=['Company'],keep='last',inplace=True,ignore_index=True)
df_sorted[['Company','Price_euros']]

      Company  Price_euros
0        Acer      2599.00
1       Apple      2858.00
2        Asus      3975.00
3       Chuwi       449.00
4        Dell      3659.40
5     Fujitsu       799.00
6      Google      2199.00
7          HP      4389.00
8      Huawei      1499.00
9          LG      2299.00
10     Lenovo      4899.00
11        MSI      2799.00
12   Mediacom       389.00
13  Microsoft      2589.00
14      Razer      6099.00
15    Samsung      1849.00
16    Toshiba      2799.00
17       Vero       260.00
18     Xiaomi      1399.95