In [1]:
import pandas as pd

In [2]:
#read csv file
df=pd.read_csv('players_20.csv')
#set index
df.set_index('short_name',inplace=True)
# select column
df=df[['long_name','age','dob','height_cm','weight_kg','nationality','club']]

In [3]:
# show dataframe
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

# .loc()
the loc[] method is used for label-based indexing — meaning you select data using row and column names (labels), not positions.

🔹 📌 Basic Idea

Access rows/columns using labels

Works with row index names and column names

Supports filtering, slicing, and assignment

🔹 ✅ Syntax

df.loc[row_labels, column_labels]

## 1. Selecting with a single value

loc[row_label,column_label]

In [4]:
#get all data about L.Messi

df.loc['L. Messi']

long_name      Lionel Andrés Messi Cuccittini
age                                        32
dob                                1987-06-24
height_cm                                 170
weight_kg                                  72
nationality                         Argentina
club                             FC Barcelona
Name: L. Messi, dtype: object

In [5]:
# get the height of l.Messi

df.loc['L. Messi','height_cm']

np.int64(170)

In [6]:
# get the weight of Cristiano Ronaldo

df.loc['Cristiano Ronaldo','weight_kg']

np.int64(83)

In [7]:
# get all rows inside the 'height_cm' column

df.loc[:,'height_cm']

short_name
L. Messi             170
Cristiano Ronaldo    187
Neymar Jr            175
J. Oblak             188
E. Hazard            175
                    ...
Shao Shuai           186
Xiao Mingjie         177
Zhang Wei            186
Wang Haijian         185
Pan Ximing           182
Name: height_cm, Length: 18278, dtype: int64

In [8]:
# get all columns that correspond to index 'L. Messi'

df.loc['L. Messi',:]

long_name      Lionel Andrés Messi Cuccittini
age                                        32
dob                                1987-06-24
height_cm                                 170
weight_kg                                  72
nationality                         Argentina
club                             FC Barcelona
Name: L. Messi, dtype: object

## 2 Selecting with a list of values

In [9]:
# get all data about L.Messi and Cristiano Ronaldo
df.loc[['L. Messi','Cristiano Ronaldo'],:]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus

In [11]:
# get the height of L. Messi,'Cristiano Ronaldo

df.loc[['L. Messi','Cristiano Ronaldo'],'height_cm']

short_name
L. Messi             170
Cristiano Ronaldo    187
Name: height_cm, dtype: int64

In [13]:
# get height and weight of L. Messi

df.loc['L. Messi',['height_cm','weight_kg']]

height_cm    170
weight_kg     72
Name: L. Messi, dtype: object

In [14]:
# get height and weight of L. Messi and Cristiano Ronaldo

df.loc[['L. Messi','Cristiano Ronaldo'],['height_cm','weight_kg']]

                   height_cm  weight_kg
short_name
L. Messi                 170         72
Cristiano Ronaldo        187         83

## 3 Selecting a range of data with a slice

start:end:stop

**Here the end value is also inlcuded**

In [16]:
# slice column labels

players=['L. Messi','Cristiano Ronaldo']

df.loc[players,'long_name':'club':2]

,long_name,dob,weight_kg,club
short_name,,,,
L. Messi,Lionel Andrés Messi Cuccittini,1987-06-24,72,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,1985-02-05,83,Juventus

In [22]:
# slice index labels
columns=['long_name','age','dob','height_cm','weight_kg','nationality','club']

# get top1 and top10 player name
df.index[:10]
df.loc['L. Messi':'M. Salah',columns]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
V. van Dijk,Virgil van Dijk,27,1991-07-08,193,92,Netherlands,Liverpool
L. Modrić,Luka Modrić,33,1985-09-09,172,66,Croatia,Real Madrid
M. Salah,Mohamed Salah Ghaly,27,1992-06-15,175,71,Egypt,Liverpool

## 4 Selecting with conditions

In [28]:
# one condition: select player with height above 180cm

df['height_cm']>180

df.loc[df['height_cm']>180,:]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
V. van Dijk,Virgil van Dijk,27,1991-07-08,193,92,Netherlands,Liverpool
...,...,...,...,...,...,...,...
P. Martin,Paul Martin,20,1999-01-05,188,84,Republic of Ireland,Waterford FC
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [31]:
# multiple conditon: select player with height above 180 cm from argentina

(df['height_cm']>180) & (df['nationality']=='Argentina')

df.loc[(df['height_cm']>180) & (df['nationality']=='Argentina'),:]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
M. Icardi,Mauro Emanuel Icardi Rivero,26,1993-02-19,181,75,Argentina,Inter
G. Higuaín,Gonzalo Gerardo Higuaín,31,1987-12-10,186,89,Argentina,Juventus
E. Garay,Ezequiel Marcelo Garay,32,1986-10-10,189,90,Argentina,Valencia CF
N. Otamendi,Nicolás Hernán Otamendi,31,1988-02-12,183,81,Argentina,Manchester City
G. Rulli,Gerónimo Rulli,27,1992-05-20,189,84,Argentina,Montpellier HSC
...,...,...,...,...,...,...,...
T. Durso,Tomás Durso,20,1999-02-26,185,80,Argentina,Gimnasia y Esgrima La Plata
J. Hass,Joaquín Hass,21,1998-03-27,186,88,Argentina,Club Atlético Colón
R. Ferrario,Rafael Ferrario,19,2000-04-30,186,76,Argentina,Club Atlético Huracán
L. Finochietto,Leandro Finochietto,22,1997-04-25,186,77,Argentina,Argentinos Juniors
N. Forastiero,Nicolás Forastiero,20,1998-07-16,182,79,Argentina,Argentinos Juniors