In [1]:
import pandas as pd

In [3]:
#read csv file
df=pd.read_csv('players_20.csv')

#set index
df.set_index('short_name',inplace=True)

# select column
df=df[['long_name','age','dob','height_cm','weight_kg','nationality','club']]

In [4]:
df.head(3)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain

# iloc()

.iloc() is used for integer-location based indexing—that means you select rows and columns by their numerical position (0-based index), not by labels.

🔹 Basic Syntax

    df.iloc[row_index, column_index]

🔹 Key Points

    Uses integer positions (0, 1, 2, …)
    Works like standard Python indexing
    Supports slicing, lists, and boolean arrays

## 1.Selecting with a single value

In [11]:
#get the height of L.Messi

row=df.index.get_loc('L. Messi')
column=df.columns.get_loc('height_cm')

df.iloc[row,column]

np.int64(170)

In [12]:
# get the weight of Cristiano Ronaldo

row=df.index.get_loc('Cristiano Ronaldo')
column=df.columns.get_loc('weight_kg')

df.iloc[row,column]

np.int64(83)

In [13]:
# get all rows inside the 'height_cm' column

column=df.columns.get_loc('height_cm')

df.iloc[:,column]

short_name
L. Messi             170
Cristiano Ronaldo    187
Neymar Jr            175
J. Oblak             188
E. Hazard            175
                    ...
Shao Shuai           186
Xiao Mingjie         177
Zhang Wei            186
Wang Haijian         185
Pan Ximing           182
Name: height_cm, Length: 18278, dtype: int64

In [14]:
# get all columns that corresponds to the index 'L. Messi'

row=df.index.get_loc('L. Messi')

df.iloc[row,:]

long_name      Lionel Andrés Messi Cuccittini
age                                        32
dob                                1987-06-24
height_cm                                 170
weight_kg                                  72
nationality                         Argentina
club                             FC Barcelona
Name: L. Messi, dtype: object

## 2.Selecting with a list of values

In [15]:
# get all data about L. Messi and Cristiano Ronaldo

row1=df.index.get_loc('L. Messi')
row2=df.index.get_loc('Cristiano Ronaldo')

df.iloc[row1:row2+1,:]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus

In [16]:
# get the height of L. Messi and Cristiano Ronaldo

row1=df.index.get_loc('L. Messi')
row2=df.index.get_loc('Cristiano Ronaldo')
column=df.columns.get_loc('height_cm')

df.iloc[row1:row2+1,column]

short_name
L. Messi             170
Cristiano Ronaldo    187
Name: height_cm, dtype: int64

In [17]:
# get the height and weight of L. Messi

row=df.index.get_loc('L. Messi')
column1=df.columns.get_loc('height_cm')
column2=df.columns.get_loc('weight_kg')

df.iloc[row,column1:column2+1]

height_cm    170
weight_kg     72
Name: L. Messi, dtype: object

In [18]:
# get the height and weight of L. Messi and Cristiano Ronaldo

row1=df.index.get_loc('L. Messi')
row2=df.index.get_loc('Cristiano Ronaldo')
column1=df.columns.get_loc('height_cm')
column2=df.columns.get_loc('weight_kg')

df.iloc[row1:row2+1,column1:column2+1]

                   height_cm  weight_kg
short_name
L. Messi                 170         72
Cristiano Ronaldo        187         83

## 3.Selecting a range of data with a slice

start:stop:step

HERE THE STOP IS NOT INCLUDED

In [32]:
# slice column labels age/club
#players=['L. Messi','Cristiano Ronaldo']

player=[0,1]

df.iloc[player,1:7]

,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,
L. Messi,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,34,1985-02-05,187,83,Portugal,Juventus

In [33]:
# slice index labels (top1 to top10 player)
# columns=['age','dob','height_cm','weight_kg']

column_index=df.columns.get_indexer(['age','dob','height_cm','weight_kg'])
df.iloc[0:10,column_index]

                   age         dob  height_cm  weight_kg
short_name
L. Messi            32  1987-06-24        170         72
Cristiano Ronaldo   34  1985-02-05        187         83
Neymar Jr           27  1992-02-05        175         68
J. Oblak            26  1993-01-07        188         87
E. Hazard           28  1991-01-07        175         74
K. De Bruyne        28  1991-06-28        181         70
M. ter Stegen       27  1992-04-30        187         85
V. van Dijk         27  1991-07-08        193         92
L. Modrić           33  1985-09-09        172         66
M. Salah            27  1992-06-15        175         71

## 4.Selecting with conditions

iloc **cannot accept a **boolean Series****,but only a **BOOLEAN LIST**.
We have to use the list() funciton to convert a Series into a boolean list.

In [40]:
#one condition: Select player with the height above 180cm
# columns=['age','dob','height_cm','weight_kg']

columns_index=df.columns.get_indexer(['age','dob','height_cm','weight_kg'])

player_list=list(df['height_cm']>180)

df.iloc[player_list,columns_index]

                   age         dob  height_cm  weight_kg
short_name
Cristiano Ronaldo   34  1985-02-05        187         83
J. Oblak            26  1993-01-07        188         87
K. De Bruyne        28  1991-06-28        181         70
M. ter Stegen       27  1992-04-30        187         85
V. van Dijk         27  1991-07-08        193         92
...                ...         ...        ...        ...
P. Martin           20  1999-01-05        188         84
Shao Shuai          22  1997-03-10        186         79
Zhang Wei           19  2000-05-16        186         75
Wang Haijian        18  2000-08-02        185         74
Pan Ximing          26  1993-01-11        182         78

[9744 rows x 4 columns]

In [42]:
# multiple conditions: select player with height above 180 cm and nationaly is argentina

player_list=list((df['height_cm']>180) & (df['nationality']=='Argentina'))
columns_index=df.columns.get_indexer(['age','dob','height_cm','weight_kg'])

df.iloc[player_list,columns_index]

                age         dob  height_cm  weight_kg
short_name
M. Icardi        26  1993-02-19        181         75
G. Higuaín       31  1987-12-10        186         89
E. Garay         32  1986-10-10        189         90
N. Otamendi      31  1988-02-12        183         81
G. Rulli         27  1992-05-20        189         84
...             ...         ...        ...        ...
T. Durso         20  1999-02-26        185         80
J. Hass          21  1998-03-27        186         88
R. Ferrario      19  2000-04-30        186         76
L. Finochietto   22  1997-04-25        186         77
N. Forastiero    20  1998-07-16        182         79

[350 rows x 4 columns]