In [1]:
import pandas as pd

In [3]:
# read csv file
df=pd.read_csv('players_20.csv')

# set index
df.set_index('short_name',inplace=True)
df
#set column
df=df[['long_name','age','dob','height_cm','weight_kg','nationality','club']]

In [4]:
# show dataframe
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

# .drop()

the .drop() method is very flexible—it can remove rows or columns depending on the parameters you pass

df.drop(labels=None, axis=0, index=None, columns=None, level=None, inplace=False, errors='raise')

1. labels


   Specifies what to delete

   
    Can be:

   
        Single label → 2

        List → [1, 3, 5]

    👉 Works for both rows and columns depending on axis

3. axis → alternative way

    axis=0 → rows
    axis=1 → columns

3.index → drop rows

4.columns → drop columns

5.inplace=True → change original DataFrame

6.errors='ignore' → avoid error if not found

 ## 1.Drop row

In [7]:
#drop 1 row
#axis paramter

df.drop(labels='L. Messi',axis=0)

#or index parameter
df.drop(index='L. Messi')

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [10]:
# drop two or more rows and update the data
df.drop(index=['Pan Ximing','Wang Haijian','Zhang Wei'],inplace=True)

In [12]:
# show dataframe
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
M. Sagaf,Mohammed Sagaf,21,1997-11-12,177,70,England,Carlisle United
E. Tweed,Evan Tweed,20,1999-03-01,180,72,Republic of Ireland,Derry City
P. Martin,Paul Martin,20,1999-01-05,188,84,Republic of Ireland,Waterford FC
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC

## 2 Drop Columns

In [15]:
#drop 1 column
#axis parameter
df.drop(labels='club',axis=1)

#columns paramter
df.drop(columns='club')

,long_name,age,dob,height_cm,weight_kg,nationality
short_name,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium
...,...,...,...,...,...,...
M. Sagaf,Mohammed Sagaf,21,1997-11-12,177,70,England
E. Tweed,Evan Tweed,20,1999-03-01,180,72,Republic of Ireland
P. Martin,Paul Martin,20,1999-01-05,188,84,Republic of Ireland
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR

In [21]:
# drop columns by position/index (drop last column)
df.columns[[-1]]

df.drop(columns=df.columns[[-1]])

,long_name,age,dob,height_cm,weight_kg,nationality
short_name,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium
...,...,...,...,...,...,...
M. Sagaf,Mohammed Sagaf,21,1997-11-12,177,70,England
E. Tweed,Evan Tweed,20,1999-03-01,180,72,Republic of Ireland
P. Martin,Paul Martin,20,1999-01-05,188,84,Republic of Ireland
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR

In [25]:
#drop 2 pr more columns and update the data

df.drop(columns=['weight_kg','nationality'],inplace=True)

In [26]:
#show dataframe
df.head()

,long_name,age,dob,height_cm,club
short_name,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,Real Madrid