In [1]:
import pandas as pd

In [2]:
# reads csv file
df = pd.read_csv('players_20.csv')

# set index
df.set_index('short_name', inplace=True)
# select column

df = df[['long_name', 'age', 'dob', 'height_cm', 'weight_kg', 'nationality', 'club']]

In [3]:
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

# query()
.query() is used to filter rows of a DataFrame using a condition written as a string.

👉 It’s an alternative to:

df[df['age'] > 18]

🔹Basic Syntax:

df.query("condition")

🔴 Important Notes:

You must pass condition as a string.

Column names are used directly (no df['col']).

Use @ for external variables

✅ Simple condition: 
df.query("age > 18")

✅ Multiple conditions: 
df.query("age > 18 and salary > 50000")

✅ Using OR: 
df.query("age > 18 or salary > 50000")

✅ Using variables (important): 

limit = 18

df.query("age > @limit")

✅ Column names with spaces: 
df.query(" `total salary` > 50000")

👉 Use backticks `

In [4]:
# select players older than 34
df.query(" age > 34 ").head()

# exercise: write the equivalent boolean indexing
df[df['age']>34].head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Z. Ibrahimović,Zlatan Ibrahimović,37,1981-10-03,195,95,Sweden,LA Galaxy
Pepe,Képler Laveran Lima Ferreira,36,1983-02-26,188,81,Portugal,FC Porto
G. Buffon,Gianluigi Buffon,41,1978-01-28,192,92,Italy,Juventus
Casillas,Iker Casillas Fernández,38,1981-05-20,185,84,Spain,FC Porto
F. Quagliarella,Fabio Quagliarella,36,1983-01-31,180,79,Italy,Sampdoria

In [5]:
# select player older than 34 and from Italy
df.query(" age>34 and nationality=='Italy' ").head()

# using boolean indexing
df[(df['age']>34) & (df['nationality']=='Italy')].head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
G. Buffon,Gianluigi Buffon,41,1978-01-28,192,92,Italy,Juventus
F. Quagliarella,Fabio Quagliarella,36,1983-01-31,180,79,Italy,Sampdoria
D. De Rossi,Daniele De Rossi,35,1983-07-24,184,83,Italy,Boca Juniors
A. Mirante,Antonio Mirante,35,1983-07-08,193,79,Italy,Roma
A. Diamanti,Alessandro Diamanti,36,1983-05-02,180,75,Italy,Western United FC

In [6]:
# add a not operator to first example
df.query("not (age>34 and nationality=='Italy') ").head()

# boolean
df[~((df['age']>34) & (df['nationality']=='Italy'))].head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

In [7]:
# convert height to meters and select those with heihgt above 1.8

df['height_m']=df['height_cm'] / 100

df.query(" height_m >1.8").head()

# boolean indexing/slicing
df[df['height_m']>1.8].head()

,long_name,age,dob,height_cm,weight_kg,nationality,club,height_m
short_name,,,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,1.87
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,1.88
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City,1.81
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona,1.87
V. van Dijk,Virgil van Dijk,27,1991-07-08,193,92,Netherlands,Liverpool,1.93

In [10]:
# select players that were born after 1990

#check datatype of dob
df.dtypes # or use df.info()

# convert 'dob' column  to datetime format.
df['dob']=df['dob'].astype('datetime64[ns]')
df['dob'].dt.year

#query
df.query(" dob.dt.year > 1990 ")

# boolean indexing
df[df['dob'].dt.year >1990]

,long_name,age,dob,height_cm,weight_kg,nationality,club,height_m
short_name,,,,,,,,
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,1.75
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,1.88
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,1.75
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City,1.81
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona,1.87
...,...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC,1.86
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC,1.77
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC,1.86
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC,1.85
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC,1.82